import { ServiceCategory } from '@/types'

export const serviceCategories: ServiceCategory[] = [
  {
    id: 'seguidores',
    title: 'Seguidores',
    icon: '👥',
    description: 'Aumente sua base de seguidores com qualidade',
    options: [
      {
        serviceId: 402,
        name: '100 Seguidores',
        description: 'Seguidores com reposição 30 dias',
        quantity: 100,
        price: 5.90,
        cost: 0.48,
      },
      {
        serviceId: 402,
        name: '500 Seguidores',
        description: 'Seguidores com reposição 30 dias',
        quantity: 500,
        price: 9.90,
        cost: 2.40,
      },
      {
        serviceId: 402,
        name: '1.000 Seguidores',
        description: 'Seguidores com reposição 30 dias',
        quantity: 1000,
        price: 14.90,
        cost: 4.80,
        popular: true,
        badge: '🔥 PROMOÇÃO',
      },
      {
        serviceId: 402,
        name: '3.000 Seguidores',
        description: 'Seguidores com reposição 30 dias',
        quantity: 3000,
        price: 34.90,
        cost: 14.40,
      },
      {
        serviceId: 402,
        name: '5.000 Seguidores',
        description: 'Seguidores com reposição 30 dias',
        quantity: 5000,
        price: 49.90,
        cost: 24.00,
        badge: 'MELHOR CUSTO',
      },
      {
        serviceId: 402,
        name: '10.000 Seguidores',
        description: 'Seguidores com reposição 30 dias',
        quantity: 10000,
        price: 89.90,
        cost: 48.00,
      },
      {
        serviceId: 415,
        name: '100 Seguidores BR',
        description: 'Seguidores brasileiros com reposição 365 dias',
        quantity: 100,
        price: 14.90,
        cost: 1.43,
        badge: '🇧🇷 BR',
      },
      {
        serviceId: 415,
        name: '500 Seguidores BR',
        description: 'Seguidores brasileiros com reposição 365 dias',
        quantity: 500,
        price: 39.90,
        cost: 7.15,
        badge: '🇧🇷 BR',
      },
      {
        serviceId: 415,
        name: '1.000 Seguidores BR',
        description: 'Seguidores brasileiros com reposição 365 dias',
        quantity: 1000,
        price: 69.90,
        cost: 14.30,
        badge: '🇧🇷 BR',
      },
    ],
  },
  {
    id: 'curtidas',
    title: 'Curtidas',
    icon: '❤️',
    description: 'Curtidas reais para engajamento',
    options: [
      {
        serviceId: 390,
        name: '100 Curtidas',
        description: 'Curtidas com reposição 365 dias',
        quantity: 100,
        price: 2.90,
        cost: 0.22,
      },
      {
        serviceId: 390,
        name: '500 Curtidas',
        description: 'Curtidas com reposição 365 dias',
        quantity: 500,
        price: 6.90,
        cost: 1.09,
      },
      {
        serviceId: 390,
        name: '1.000 Curtidas',
        description: 'Curtidas com reposição 365 dias',
        quantity: 1000,
        price: 9.90,
        cost: 2.18,
        popular: true,
        badge: '🔥 PROMOÇÃO',
      },
      {
        serviceId: 390,
        name: '5.000 Curtidas',
        description: 'Curtidas com reposição 365 dias',
        quantity: 5000,
        price: 39.90,
        cost: 10.90,
        badge: 'MELHOR CUSTO',
      },
      {
        serviceId: 335,
        name: '100 Curtidas BR',
        description: 'Curtidas brasileiras 100% reais',
        quantity: 100,
        price: 5.90,
        cost: 0.63,
        badge: '🇧🇷 BR',
      },
      {
        serviceId: 335,
        name: '500 Curtidas BR',
        description: 'Curtidas brasileiras 100% reais',
        quantity: 500,
        price: 17.90,
        cost: 3.16,
        badge: '🇧🇷 BR',
      },
      {
        serviceId: 335,
        name: '1.000 Curtidas BR',
        description: 'Curtidas brasileiras 100% reais',
        quantity: 1000,
        price: 29.90,
        cost: 6.32,
        badge: '🇧🇷 BR',
      },
    ],
  },
  {
    id: 'visualizacoes',
    title: 'Visualizações',
    icon: '👁️',
    description: 'Visualizações para Reels, Stories e Posts',
    options: [
      {
        serviceId: 11,
        name: '1.000 Visualizações Reels',
        description: 'Visualizações de Reels, entrega em até 24h',
        quantity: 1000,
        price: 2.90,
        cost: 0.04,
      },
      {
        serviceId: 11,
        name: '5.000 Visualizações Reels',
        description: 'Visualizações de Reels, entrega em até 24h',
        quantity: 5000,
        price: 5.90,
        cost: 0.20,
      },
      {
        serviceId: 11,
        name: '10.000 Visualizações Reels',
        description: 'Visualizações de Reels, entrega em até 24h',
        quantity: 10000,
        price: 7.90,
        cost: 0.40,
        popular: true,
        badge: '🔥 PROMOÇÃO',
      },
      {
        serviceId: 11,
        name: '50.000 Visualizações Reels',
        description: 'Visualizações de Reels, entrega em até 24h',
        quantity: 50000,
        price: 19.90,
        cost: 2.00,
        badge: 'MELHOR CUSTO',
      },
      {
        serviceId: 11,
        name: '100.000 Visualizações Reels',
        description: 'Visualizações de Reels, entrega em até 24h',
        quantity: 100000,
        price: 34.90,
        cost: 4.00,
      },
      {
        serviceId: 413,
        name: '100 Visualizações Story',
        description: 'Visualizações de Story ultra rápidas',
        quantity: 100,
        price: 2.90,
        cost: 0.19,
      },
      {
        serviceId: 413,
        name: '500 Visualizações Story',
        description: 'Visualizações de Story ultra rápidas',
        quantity: 500,
        price: 6.90,
        cost: 0.94,
      },
      {
        serviceId: 413,
        name: '1.000 Visualizações Story',
        description: 'Visualizações de Story ultra rápidas',
        quantity: 1000,
        price: 9.90,
        cost: 1.87,
      },
      {
        serviceId: 416,
        name: '100 Visualizações Post',
        description: 'Visualizações para Post ou Carrossel',
        quantity: 100,
        price: 2.90,
        cost: 0.24,
      },
      {
        serviceId: 416,
        name: '500 Visualizações Post',
        description: 'Visualizações para Post ou Carrossel',
        quantity: 500,
        price: 6.90,
        cost: 1.19,
      },
      {
        serviceId: 416,
        name: '1.000 Visualizações Post',
        description: 'Visualizações para Post ou Carrossel',
        quantity: 1000,
        price: 9.90,
        cost: 2.38,
      },
    ],
  },
  {
    id: 'comentarios',
    title: 'Comentários',
    icon: '💬',
    description: 'Comentários reais para engajamento',
    options: [
      {
        serviceId: 357,
        name: '10 Comentários',
        description: 'Comentários aleatórios unissex',
        quantity: 10,
        price: 9.90,
        cost: 0.21,
      },
      {
        serviceId: 357,
        name: '50 Comentários',
        description: 'Comentários aleatórios unissex',
        quantity: 50,
        price: 34.90,
        cost: 1.06,
        popular: true,
        badge: '🔥 PROMOÇÃO',
      },
      {
        serviceId: 357,
        name: '100 Comentários',
        description: 'Comentários aleatórios unissex',
        quantity: 100,
        price: 59.90,
        cost: 2.11,
        badge: 'MELHOR CUSTO',
      },
      {
        serviceId: 288,
        name: '10 Comentários BR',
        description: 'Comentários personalizados brasileiros',
        quantity: 10,
        price: 79.90,
        cost: 2.40,
        badge: '🇧🇷 BR',
      },
      {
        serviceId: 288,
        name: '50 Comentários BR',
        description: 'Comentários personalizados brasileiros',
        quantity: 50,
        price: 349.90,
        cost: 12.00,
        badge: '🇧🇷 BR',
      },
    ],
  },
  {
    id: 'extras',
    title: 'Extras',
    icon: '🚀',
    description: 'Alcance, impressões e compartilhamentos',
    options: [
      {
        serviceId: 377,
        name: '1.000 Compartilhamentos',
        description: 'Compartilhamentos de alta qualidade',
        quantity: 1000,
        price: 2.90,
        cost: 0.27,
        popular: true,
        badge: '🔥 PROMOÇÃO',
      },
      {
        serviceId: 377,
        name: '5.000 Compartilhamentos',
        description: 'Compartilhamentos de alta qualidade',
        quantity: 5000,
        price: 9.90,
        cost: 1.35,
      },
      {
        serviceId: 381,
        name: '1.000 Alcance+Impressões',
        description: 'Alcance + Impressões + Visitas no perfil',
        quantity: 1000,
        price: 4.90,
        cost: 0.75,
      },
      {
        serviceId: 381,
        name: '5.000 Alcance+Impressões',
        description: 'Alcance + Impressões + Visitas no perfil',
        quantity: 5000,
        price: 14.90,
        cost: 3.75,
      },
      {
        serviceId: 381,
        name: '10.000 Alcance+Impressões',
        description: 'Alcance + Impressões + Visitas no perfil',
        quantity: 10000,
        price: 24.90,
        cost: 7.50,
        badge: 'MELHOR CUSTO',
      },
      {
        serviceId: 417,
        name: '1.000 Reposts',
        description: 'Reposts em publicação',
        quantity: 1000,
        price: 24.90,
        cost: 6.43,
      },
    ],
  },
]

export function getServiceById(id: number): { service: ServiceCategory['options'][0]; category: ServiceCategory } | null {
  for (const category of serviceCategories) {
    const option = category.options.find(o => o.serviceId === id)
    if (option) {
      return { service: option, category }
    }
  }
  return null
}
